# Default values for openldap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

openldap:
  name: "openldap"
  port: 1389
  adminUser: "admin"
  adminPassword: "adminpassword"
  image: "docker.io/bitnami/openldap:latest"
  isPersistent: true
  pvcSize: "1Gi"
phpldapadmin:
  name: "phpldapadmin"
  port: 80
  portHttps: 443
  image: "osixia/phpldapadmin:latest"
  isHttps: false