apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.openldap.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.openldap.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.openldap.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.openldap.name }}
    spec:
      containers:
        - name: {{ .Values.openldap.name }}
          image: {{ .Values.openldap.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: LDAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: adminuser
                  name: {{ .Values.openldap.name }}-credential
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: {{ .Values.openldap.name }}-credential
          ports:
            - name: tcp-ldap
              containerPort: 1389
          volumeMounts:
          - name: ldif-volume
            mountPath: /ldifs
          {{- if .Values.openldap.isPersistent }}
          - name: {{ .Values.openldap.name }}-data
            mountPath: /bitnami/openldap
          {{- end }}
      volumes:
        - name: ldif-volume
          configMap:
            name: {{ .Values.openldap.name }}-ldif-file
        {{- if .Values.openldap.isPersistent }}
        - name: {{ .Values.openldap.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.openldap.name }}-data
        {{- end }}