apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openldap.name }}-credential
type: Opaque
stringData:
  adminuser: {{ .Values.openldap.adminUser }}
  adminpassword: {{ .Values.openldap.adminPassword }}