apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openldap.name }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: {{ .Values.openldap.port }}
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: {{ .Values.openldap.name }}